env:
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
overrides:
  [{ files: ['*.js'], rules: { no-console: off, import/extensions: off } }]
